#!/bin/bash
CXX=${CXX:-clang++}
$CXX -std=c++23 -stdlib=libc++ -fexperimental-library -O3 -Wall -o o2l \
    src/main.cpp \
    src/Lexer.cpp \
    src/Parser.cpp \
    src/Interpreter.cpp \
    src/AST/Node.cpp \
    src/AST/ObjectNode.cpp \
    src/AST/MethodCallNode.cpp \
    src/AST/MethodDeclarationNode.cpp \
    src/AST/ConstructorDeclarationNode.cpp \
    src/AST/IdentifierNode.cpp \
    src/AST/ImportNode.cpp \
    src/AST/NewExpressionNode.cpp \
    src/AST/PropertyAccessNode.cpp \
    src/AST/PropertyAssignmentNode.cpp \
    src/AST/ThisNode.cpp \
    src/AST/PropertyDeclarationNode.cpp \
    src/AST/FunctionCallNode.cpp \
    src/AST/ConstDeclarationNode.cpp \
    src/AST/VariableDeclarationNode.cpp \
    src/AST/VariableAssignmentNode.cpp \
    src/AST/BlockNode.cpp \
    src/AST/LiteralNode.cpp \
    src/AST/BinaryOpNode.cpp \
    src/AST/ReturnNode.cpp \
    src/AST/IfStatementNode.cpp \
    src/AST/WhileStatementNode.cpp \
    src/AST/BreakNode.cpp \
    src/AST/ContinueNode.cpp \
    src/AST/SpawnNode.cpp \
    src/AST/ComparisonNode.cpp \
    src/AST/LogicalNode.cpp \
    src/AST/UnaryNode.cpp \
    src/AST/EnumDeclarationNode.cpp \
    src/AST/EnumAccessNode.cpp \
    src/AST/RecordDeclarationNode.cpp \
    src/AST/RecordInstantiationNode.cpp \
    src/AST/RecordFieldAccessNode.cpp \
    src/AST/MemberAccessNode.cpp \
    src/AST/ProtocolDeclarationNode.cpp \
    src/AST/NamespaceNode.cpp \
    src/AST/QualifiedIdentifierNode.cpp \
    src/AST/ThrowNode.cpp \
    src/AST/TryCatchFinallyNode.cpp \
    src/AST/JsonSerializer.cpp \
    src/Runtime/Value.cpp \
    src/Runtime/Coroutine.cpp \
    src/Runtime/ObjectInstance.cpp \
    src/Runtime/Context.cpp \
    src/Runtime/ModuleLoader.cpp \
    src/Runtime/SystemLibrary.cpp \
    src/Runtime/MathLibrary.cpp \
    src/Runtime/TestLibrary.cpp \
    src/Runtime/DateTimeLibrary.cpp \
    src/Runtime/RegexpLibrary.cpp \
    src/Runtime/UrlLibrary.cpp \
    src/Runtime/JsonLibrary.cpp \
    src/Runtime/HttpClientLibrary.cpp \
    src/Runtime/HttpServerLibrary.cpp \
    src/Runtime/EnumInstance.cpp \
    src/Runtime/RecordType.cpp \
    src/Runtime/RecordInstance.cpp \
    src/Runtime/ProtocolInstance.cpp \
    src/Runtime/ListInstance.cpp \
    src/Runtime/ListIterator.cpp \
    src/Runtime/RepeatIterator.cpp \
    src/Runtime/MapInstance.cpp \
    src/Runtime/MapIterator.cpp \
    src/Runtime/MapObject.cpp \
    src/Runtime/SetInstance.cpp \
    src/Runtime/SetIterator.cpp \
    src/Runtime/ErrorInstance.cpp \
    src/Runtime/ResultInstance.cpp \
    src/Runtime/NativeLibrary.cpp \
    src/Runtime/DynamicLibraryManager.cpp \
    src/Runtime/FFILibrary.cpp \
    src/Runtime/FFI/SharedLibrary.cpp \
    src/Runtime/FFI/FFITypes.cpp \
    src/Runtime/FFI/FFIEngine.cpp \
    src/Runtime/IOThreadPool.cpp \
    src/Runtime/Scheduler.cpp \
    src/Runtime/ConcurrencyLibrary.cpp \
    src/Runtime/ChannelInstance.cpp \
    src/Runtime/CompilerLibrary.cpp \
    src/Runtime/BinaryLibrary.cpp \
    src/Runtime/BitLibrary.cpp \
    src/Common/Exceptions.cpp \
    -Isrc -L/usr/lib/x86_64-linux-gnu -ldl -l:libffi.so.8
